name: Google Cloud Authentication using Workload Identity Federation
inputs:
  gcp_workload_identity_provider:
    type: string
    required: true
  gcp_service_account_email:
    type: string
    required: true
  gke_cluster_name:
    type: string
    default: ""
    required: false
  gke_location:
    type: string
    default: ""
    required: false

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account_email }}

    - name: Set up Google Cloud SDK
      uses: "google-github-actions/setup-gcloud@v1"

    - name: Fetch GKE Credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_location }}
      if: inputs.gke_cluster_name != '' && inputs.gke_location != ''
